import type { Metadata } from "next";

import "./globals.css";
import { inter } from "@/app/fonts/fonts";
import { NextUIProvider } from "@nextui-org/react";

export const metadata: Metadata = {
  title: "Zyptyk",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <NextUIProvider>
        <body className={`${inter.className} antialiased`}>{children}</body>
      </NextUIProvider>
    </html>
  );
}
